"""initial schema

Revision ID: 8cabd6742cb7
Revises:
Create Date: 2026-09-16 12:22:18.044689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cabd6742cb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('shop_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('shop_address', sa.Text(), server_default='', nullable=False),
    sa.Column('shop_tax_id', sa.String(length=20), server_default='', nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), server_default='7', nullable=False),
    sa.Column('repair_warranty_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('dead_stock_days', sa.Integer(), server_default='90', nullable=False),
    sa.CheckConstraint('dead_stock_days > 0', name=op.f('ck_settings_dead_stock_days')),
    sa.CheckConstraint('id = 1', name=op.f('ck_settings_single_row')),
    sa.CheckConstraint('repair_warranty_days >= 0', name=op.f('ck_settings_warranty_days')),
    sa.CheckConstraint('vat_rate >= 0', name=op.f('ck_settings_vat_rate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('admin','employee','mechanic')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.execute("insert into settings (id) values (1)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('settings')
    # ### end Alembic commands ###
