"""settings

Revision ID: c147fc9bcaca
Revises: a04331d7fcb7
Create Date: 2026-09-20 14:28:19.327159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c147fc9bcaca'
down_revision: Union[str, Sequence[str], None] = 'a04331d7fcb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('shop_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('shop_address', sa.Text(), server_default='', nullable=False),
    sa.Column('shop_tax_id', sa.String(length=20), server_default='', nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), server_default='7', nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_settings_single_row')),
    sa.CheckConstraint('vat_rate >= 0', name=op.f('ck_settings_vat_rate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.execute("insert into settings (id) values (1)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
