"""products lots and movements

Revision ID: cf2321ce1e3d
Revises: c147fc9bcaca
Create Date: 2026-09-22 07:53:45.611598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2321ce1e3d'
down_revision: Union[str, Sequence[str], None] = 'c147fc9bcaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('min_stock >= 0', name=op.f('ck_products_min_stock')),
    sa.CheckConstraint('sale_price >= 0', name=op.f('ck_products_sale_price')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('code', name=op.f('uq_products_code'))
    )
    op.create_table('stock_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=12), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type in ('adjustment','opening')", name=op.f('ck_stock_lots_source_type')),
    sa.CheckConstraint('qty_received > 0 and qty_remaining >= 0 and qty_remaining <= qty_received', name=op.f('ck_stock_lots_qty')),
    sa.CheckConstraint('unit_cost >= 0 and cost_total >= 0', name=op.f('ck_stock_lots_cost')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_lots_created_by_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_lots_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_lots'))
    )
    op.create_index(op.f('ix_stock_lots_created_by'), 'stock_lots', ['created_by'], unique=False)
    op.create_index('ix_stock_lots_fifo', 'stock_lots', ['product_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_stock_lots_product_id'), 'stock_lots', ['product_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('movement_type', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(movement_type = 'opening' and qty > 0) or (movement_type = 'adjust' and qty <> 0)", name=op.f('ck_stock_movements_direction')),
    sa.CheckConstraint("movement_type <> 'adjust' or reason is not null", name=op.f('ck_stock_movements_adjust_reason')),
    sa.CheckConstraint("movement_type in ('adjust','opening')", name=op.f('ck_stock_movements_type')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_movements_created_by_users')),
    sa.ForeignKeyConstraint(['lot_id'], ['stock_lots.id'], name=op.f('fk_stock_movements_lot_id_stock_lots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index(op.f('ix_stock_movements_created_by'), 'stock_movements', ['created_by'], unique=False)
    op.create_index(op.f('ix_stock_movements_lot_id'), 'stock_movements', ['lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_lot_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_by'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_stock_lots_product_id'), table_name='stock_lots')
    op.drop_index('ix_stock_lots_fifo', table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_created_by'), table_name='stock_lots')
    op.drop_table('stock_lots')
    op.drop_table('products')
    # ### end Alembic commands ###
